# Generated by Django 4.2.7 on 2023-11-24 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id_produk', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=255)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategori_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manajemen.kategori')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manajemen.status')),
            ],
        ),
    ]
